const Map<String, String> enTranslations = {
  'loginTitle': 'Login',
  'welcomeMessage': 'Welcome to Movexa!',
  'trackingSteps': 'Track your steps',
  'loginWithGoogle': 'Login with Google',
  'continueToApp': 'Continue to App',
  'onboardingDesc': 'This is your setup page to be developed next.',
  'setNewGoal': 'Set New Goal',
  'setDailyStepGoal': 'Set your daily step goal',
  'cancel': 'Cancel',
  'newGoalSet': 'New goal set: ',
  'save': 'Save',
  'logoutAccount': 'Log out of account?',
  'confirmLogout': 'Are you sure you want to log out?',
  'logout': 'Log Out',
  'settings': 'Settings',
  'account': 'Account',
  'personalInfo': 'Personal Info',
  'stepGoal': 'Step Goal',
  'preferences': 'Preferences',
  'darkMode': 'Dark Mode',
  'language': 'Language',
  'logoutAction': 'Log Out',
  'stepsToday': 'Steps Today',
  'calories': 'Calories',
  'distance': 'Distance',
  'durationMins': 'Duration (mins)',
  'recentActivities': 'Recent Activities',
  'seeAll': 'See All',
  'noRecentActivities': 'No recent activities',
  'motionPermissionRequired': 'Motion permission required to track steps',
  'workout': 'Workout',
  'greatJob': 'Great Job!',
  'dontGiveUp': 'Don\'t give up!',
  'goalReached': 'You reached your goal today.',
  'startingIsSuccess': 'Starting is a success.',
  'duration': 'Duration',
  'steps': 'Steps',
  'close': 'Close',
  'stop': 'Stop',
  'start': 'Start',
  'details': 'Details',
  'totalSteps': 'Total Steps',
  'minutes': 'Minutes',
  'speed': 'Speed',
  'kmPerHour': 'km/h',
  'stepsPerMin': 'steps/min',
  'editProfile': 'Edit Profile',
  'name': 'Name',
  'aboutMe': 'About Me',
  'age': 'Age',
  'weight': 'Weight',
  'height': 'Height',
  'savedSuccessfully': 'Saved successfully!',
  'activityHistory': 'Activity History',
  'daily': 'Daily',
  'noDataYet': 'No data yet',
  'summaryFor': 'Summary for',
  'dashboard': 'Dashboard',
  'history': 'History',
  'profile': 'Profile',
  'monthlyAvg': 'Monthly Avg',
  'goalReachedShort': 'Goal Reached',
  'inProgress': 'In Progress',
  'failed': 'Failed',
  'pleaseEnterValidNumber': 'Please enter a valid number',
  'hello': 'Hello!',
  'keepGoing': 'Keep going! You are doing great today.',
  'loginWithGoogleSubtitle': 'Sign in with your Google account',
  'ofGoal': 'OF GOAL',
  'motionPermissionDenied': 'Motion permission denied',
  'runOnBackgroundApp': 'Run on background app',
  'walkingNow': 'Walking now',
  'trackingStopped': 'Tracking • stopped',
  'trackingActive': 'Tracking active',
  'dailyTrackRecord': 'Daily Track Record',
};
