const Map<String, String> khTranslations = {
  'loginTitle': 'ចូលគណនី',
  'welcomeMessage': 'សូមស្វាគមន៍មកកាន់ Movexa!',
  'trackingSteps': 'តាមដានជំហានរបស់អ្នក',
  'loginWithGoogle': 'ចូលគណនីតាម Google',
  'continueToApp': 'បន្តទៅកាន់កម្មវិធី',
  'onboardingDesc':
      'នេះគឺជាទំព័ររៀបចំគណនីរបស់អ្នក ដែលនឹងត្រូវបានអភិវឌ្ឍន៍បន្ថែមនៅជំហានបន្ទាប់។',
  'setNewGoal': 'កំណត់គោលដៅថ្មី',
  'setDailyStepGoal': 'កំណត់គោលដៅជំហានប្រចាំថ្ងៃរបស់អ្នក',
  'cancel': 'បោះបង់',
  'newGoalSet': 'បានកំណត់គោលដៅថ្មី: ',
  'save': 'រក្សាទុក',
  'logoutAccount': 'ចាកចេញពីគណនី?',
  'confirmLogout': 'តើអ្នកពិតជាចង់ចាកចេញពីគណនីមែនទេ?',
  'logout': 'ចាកចេញ',
  'settings': 'ការកំណត់',
  'account': 'គណនី',
  'personalInfo': 'ព័ត៌មានផ្ទាល់ខ្លួន',
  'stepGoal': 'គោលដៅជំហាន',
  'preferences': 'ចំណូលចិត្ត',
  'darkMode': 'ម៉ូដងងឹត',
  'language': 'ភាសា',
  'logoutAction': 'ចាកចេញ',
  'stepsToday': 'ជំហាននៅថ្ងៃនេះ',
  'calories': 'កាឡូរី',
  'distance': 'ចម្ងាយ',
  'durationMins': 'រយៈពេល',
  'recentActivities': 'សកម្មភាពថ្មីៗ',
  'seeAll': 'មើលទាំងអស់',
  'noRecentActivities': 'មិនទាន់មានសកម្មភាពថ្មីៗទេ',
  'motionPermissionRequired': 'ត្រូវការសិទ្ធិចលនាដើម្បីតាមដានជំហាន',
  'workout': 'ការហាត់ប្រាណ',
  'greatJob': 'ធ្វើបានល្អណាស់!',
  'dontGiveUp': 'កុំបោះបង់!',
  'goalReached': 'អ្នកបានសម្រេចគោលដៅថ្ងៃនេះ។',
  'startingIsSuccess': 'ការចាប់ផ្តើមគឺជាភាពជោគជ័យមួយ។',
  'duration': 'រយៈពេល',
  'steps': 'ជំហាន',
  'close': 'បិទ',
  'stop': 'បញ្ឈប់',
  'start': 'ចាប់ផ្តើម',
  'details': 'សេចក្តីលម្អិត',
  'totalSteps': 'សរុបជំហាន',
  'minutes': 'នាទី',
  'speed': 'ល្បឿន',
  'kmPerHour': 'គីឡូម៉ែត្រ/ម៉ោង',
  'stepsPerMin': 'ជំហាន/នាទី',
  'editProfile': 'កែប្រែប្រវត្តិរូប',
  'name': 'ឈ្មោះ',
  'aboutMe': 'អំពីខ្ញុំ',
  'age': 'អាយុ',
  'weight': 'ទម្ងន់',
  'height': 'កម្ពស់',
  'savedSuccessfully': 'បានរក្សាទុកដោយជោគជ័យ!',
  'activityHistory': 'ប្រវត្តិសកម្មភាព',
  'daily': 'ប្រចាំថ្ងៃ',
  'noDataYet': 'មិនទាន់មានទិន្នន័យ',
  'summaryFor': 'សេចក្តីសង្ខេប ថ្ងៃទី ',
  'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
  'history': 'ប្រវត្តិ',
  'profile': 'ប្រវត្តិរូប',
  'monthlyAvg': 'មធ្យមប្រចាំខែ',
  'goalReachedShort': 'សម្រេចគោលដៅ',
  'inProgress': 'កំពុងដំណើរការ',
  'failed': 'បរាជ័យ',
  'pleaseEnterValidNumber': 'សូមបញ្ចូលចំនួនឲ្យបានត្រឹមត្រូវ',
  'hello': 'សួស្តី!',
  'keepGoing': 'បន្តដំណើរ! ថ្ងៃនេះល្អណាស់',
  'loginWithGoogleSubtitle': 'ចូលគណនីតាមរយៈ Google របស់អ្នក',
  'ofGoal': 'នៃគោលដៅ',
  'motionPermissionDenied': 'មិនបានអនុញ្ញាតសិទ្ធិចលនា',
  'runOnBackgroundApp': 'ដំណើរការនៅផ្ទៃខាងក្រោយកម្មវិធី',
  'walkingNow': 'កំពុងដើរ',
  'trackingStopped': 'ការតាមដាន • បានបញ្ឈប់',
  'trackingActive': 'ការតាមដានកំពុងសកម្ម',
  'dailyTrackRecord': 'កំណត់ត្រាតាមដានប្រចាំថ្ងៃ',
  'aboutUs': 'អំពីយើង',
  'deleteWorkout': 'លុបការហាត់ប្រាណ',
  'confirmDeleteWorkout': 'តើអ្នកពិតជាចង់លុបការហាត់ប្រាណនេះមែនទេ?',
  'delete': 'លុប',
  'saveImage': 'រក្សាទុករូបភាព',
  'imageSaved': 'បានរក្សាទុករូបភាពក្នុងវិចិត្រសាល!',
  'download': 'រក្សាទុក',
  'appSlogan': 'កម្មវិធី\nដែលឲ្យអ្នក\nធ្វើចលនា',
  'continueWithGoogle': 'បន្តជាមួយ Google',
};
